### ISSUE TITLE
[Error] I can't "Login with OpenShock"

### ISSUE THREAD

**Issue by ROOTBEEROFF** [OpenShock/ShockOSC#36]
### Pre-submission checklist

- [x] I checked that no other Error or Bug Report describing my problem exists.
- [X] I am running the latest stable or prerelease version of ShockOSC.
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### OS

Windows 11

### Paste your error / exception stack trace here

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenShock.ShockOsc.Ui.Pages.Authentication.LoginPart.GetToken()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### ShockOSC version

v2.3.1

### Describe what you were doing when the error occoured as precisely as possible.

First time using it, can't login.

**Comment by hhvrc** [comment]
Are you running it against the official instance or a selfhosted one?

**Comment by LucHeart** [comment]
@ROOTBEEROFF that would also be my question. Cause that really shouldnt be failing there unless there so some other network proxy or something.

**Comment by ROOTBEEROFF** [comment]
Well, I guess the official one. I don't know. It's the first time I'm using it, and I'm just following the basic setup, but the current information doesn't really add up anymore. Am I supposed to put a token under Advanced Settings before I click on "Login with openshock "?

Login to ShockOSC
Open ShockOSC
Click on "Get Token", this will open a browser window.
In the browser, log into your Shocklink account and accept the request shown.
ShockOSC will now log you in.

**Comment by ROOTBEEROFF** [comment]
It seem like my network block the access to the openshock.app, if i want to download your Flashtool it get an error

`This site can’t be reached
The webpage at https://next.openshock.app/flashtool might be temporarily down or it may have moved permanently to a new web address.

ERR_QUIC_PROTOCOL_ERROR`

**Comment by ROOTBEEROFF** [comment]
My internet provider has an app for configuring everything, and they're very security-conscious. For some reason, their app was blocking access to your website. I apologize, it was a problem on my end.
